Fix variable scope errors by adding executing assembly reference
The issue was that complex objects (like DB, CODDOC, ACTIVITY) were being
stored in the object store and accessed via VBCodeExecutor.GetStoredObject(),
but the dynamically compiled code didn't have a reference to the executing
assembly where VBCodeExecutor is defined.

This caused BC30451 compilation errors saying variables were not declared,
when in reality the VBCodeExecutor module itself was inaccessible.

Changes:
- Added System.Reflection.Assembly.GetExecutingAssembly() to the references
  array in ExecuteVBCodeInternal() at VBCodeExecutor.vb:259
- This allows dynamically compiled code to access VBCodeExecutor.GetStoredObject()
  to retrieve complex objects from the object store
- Added TestComplexVariables.vb to test complex object variable injection

Fixes compilation errors for dictionary variables containing complex objects.